<!-- Generated by `cargo run --bin render-docs`; do not edit directly. -->

# {{docs.guide.title}}

{{language_switcher}}

{{docs.guide.intro}}

## {{docs.guide.overview_title}}

{{docs.guide.overview_body}}

## {{docs.guide.workflow_title}}

{{docs.guide.workflow_body}}

## {{docs.guide.recipes_title}}

{{docs.guide.recipes_body}}

## {{docs.guide.repl_title}}

{{docs.guide.repl_body}}

## {{docs.guide.reference_title}}

| {{docs.guide.command_header}} | {{docs.guide.behavior_header}} |
|---|---|
| `axec run [--name NAME] [--timeout N] [--terminate] [--stopword REGEX] [--backend pty\|pipe\|auto] [--cwd DIR] [--env K=V]... <cmd> [args]` | {{docs.guide.row_run}} |
| `axec run --backend pipe <cmd>` | {{docs.guide.row_run_backend}} |
| `axec cat [--session UUID\|NAME] [--follow] [--stderr]` | {{docs.guide.row_cat}} |
| `axec output [--session UUID\|NAME]` | {{docs.guide.row_output}} |
| `axec list` | {{docs.guide.row_list}} |
| `axec input [--session UUID\|NAME] [--timeout N] [--stopword REGEX] [--terminate] <text>` | {{docs.guide.row_input}} |
| `axec signal [--session UUID\|NAME] <SIGNAL>` | {{docs.guide.row_signal}} |
| `axec kill --session UUID\|NAME` / `axec kill --all` | {{docs.guide.row_kill}} |
| `axec clean` / `axec clear` | {{docs.guide.row_clean}} |
| `axec attach --session UUID\|NAME` | {{docs.guide.row_attach}} |

## {{docs.guide.repl_reference_title}}

| {{docs.guide.command_header}} | {{docs.guide.behavior_header}} |
|---|---|
| `axrepl run [--name NAME] [--driver python\|node\|bash\|zsh] [--cwd DIR] [--env K=V]... <cmd> [args]` | {{docs.guide.row_repl_run}} |
| `axrepl input [--session UUID\|NAME] [--driver python\|node\|bash\|zsh] <text\|->` | {{docs.guide.row_repl_input}} |
| `axrepl list` | {{docs.guide.row_repl_list}} |
| `axrepl kill --session UUID\|NAME` / `axrepl kill --all` | {{docs.guide.row_repl_kill}} |
| `axrepl clean` | {{docs.guide.row_repl_clean}} |

## {{docs.guide.output_modes_title}}

{{docs.guide.output_modes_body}}

## {{docs.guide.selection_title}}

{{docs.guide.selection_body}}

## {{docs.guide.localization_title}}

{{docs.guide.localization_body}}

```bash
{{docs.guide.localization_example}}
```

## {{docs.guide.files_title}}

{{docs.guide.files_body}}
