<!-- Generated by `cargo run --bin render-docs`; do not edit directly. -->

# {{docs.readme.title}}

{{language_switcher}}

{{docs.readme.tagline}}

{{docs.readme.summary}}

## {{docs.readme.quick_start_title}}

```bash
{{docs.readme.quick_start_commands}}
```

## {{docs.readme.docs_title}}

{{docs.readme.docs_links}}

## {{docs.readme.build_title}}

{{docs.readme.build_body}}

```bash
{{docs.readme.build_commands}}
```

## {{docs.readme.license_title}}

{{docs.readme.license_body}}
